//
// Created by Ferdinand Vanmaele on 12.01.26.
//

#ifndef GPE_GRID_H
#define GPE_GRID_H

#include <deal.II/grid/tria.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_out.h>

namespace gpe
{

/**
 * @brief A wrapper around `dealii::Triangulation` to generate and refine hypercube domains.
 *
 * This struct simplifies the creation of square (2D) or cubic (3D) domains, offering
 * the choice between quadrilateral/hexahedral meshes (standard deal.II behavior) or
 * simplicial meshes (triangles/tetrahedra).
 *
 * It encapsulates the generation logic using `dealii::GridGenerator` and handles
 * global refinement to reach a target number of multigrid levels.
 *
 * @tparam dim The spatial dimension of the domain.
 */
template <int dim>
struct HyperCube
{
    /** The underlying deal.II triangulation object. */
    dealii::Triangulation<dim> triangulation;

    /** Flag indicating if the mesh consists of simplices (true) or quads/hexes (false). */
    const bool has_simplex = false;

    /**
     * @brief Constructs a hypercube domain $[-radius, radius]^{\text{dim}}$.
     *
     * @param radius The half-width of the cube. The domain extends from -radius to +radius.
     * @param simplex_mesh If `true`, the domain is tessellated with simplices (triangles in 2D,
     * tetrahedra in 3D). If `false`, it uses hyperrectangles (quads in 2D, hexes in 3D).
     */
    HyperCube(const double radius, bool simplex_mesh) : has_simplex(simplex_mesh)
    {
        simplex_mesh ? simplex(radius) : quadrilateral(radius);
    }

    /**
     * @brief Refines the triangulation globally to reach a specific number of levels.
     *
     * Performs `n_levels - 1` global refinement steps. This assumes the coarse mesh
     * generated by the constructor represents level 1.
     *
     * @param n_levels The target total number of levels in the multigrid hierarchy.
     */
    void refine(unsigned int n_levels)
    {
        // Assert that we are requesting at least 1 level (the coarse mesh itself)
        Assert(n_levels > 0, dealii::ExcMessage("n_levels must be >= 1"));

        if (n_levels > 1) {
            triangulation.refine_global(n_levels - 1); // #cells *= 2^(dim) per step
        }
        AssertDimension(n_levels, triangulation.n_global_levels());
    }

private:
    /**
     * @brief Helper to generate a simplex mesh.
     *
     * Generates a temporary hypercube and converts it to a simplex mesh using
     * `dealii::GridGenerator::convert_hypercube_to_simplex_mesh`.
     */
    void simplex(double radius)
    {
        dealii::Triangulation<dim> tmp;
        dealii::GridGenerator::hyper_cube(tmp, -radius, radius);

        // uses default number of subdivisions (dim==2 ? 8u : 24u)
        // Note: converting before refinement ensures the coarse grid is simplicial,
        // allowing consistent refinement of simplices.
        dealii::GridGenerator::convert_hypercube_to_simplex_mesh(tmp, triangulation);
    }

    /**
     * @brief Helper to generate a standard quadrilateral/hexahedral mesh.
     */
    void quadrilateral(double radius)
    {
        dealii::GridGenerator::hyper_cube(triangulation, -radius, radius);
    }
};

/**
 * @brief Writes the grid to a file in a specified format.
 *
 * A utility wrapper around `dealii::GridOut`.
 *
 * @tparam dim Dimension of the grid.
 * @param filename The full path/name of the file to write to.
 * @param triangulation The triangulation object to output.
 * @param format The deal.II output format (e.g., vtk, svg, eps).
 */
template <int dim>
void write_grid(const std::string& filename, const dealii::Triangulation<dim>& triangulation,
    const dealii::GridOut::OutputFormat format)
{
    std::ofstream out(filename);
    const dealii::GridOut grid_out;

    grid_out.write(triangulation, out, format);
}

/**
 * @brief Writes a 2D grid to an SVG file.
 *
 * Specialized helper for visualizing 2D triangulations. Useful for debugging
 * mesh quality or refinement patterns quickly in a web browser or vector editor.
 *
 * @param s The filename to write to (e.g., "grid.svg").
 * @param triangulation The 2D triangulation object.
 */
inline void
write_grid_svg(const std::string& s, const dealii::Triangulation<2>& triangulation)
{
    write_grid(s, triangulation, dealii::GridOut::OutputFormat::svg);
}

}
#endif //GPE_GRID_H